In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [15]:
csv_file = r'd:\OneDrive\OneDrive - uniroma1.it\Università\Tesi Master\plots\Racetrack\exp_data\16_acts_vpp_from_area_2\experiment_data_02_21-14-17.csv'
df = pd.read_csv(csv_file)
df.head()

,elapsed_steps,state,agent_location_x,agent_location_y,target_location_x,target_location_y,piezo,vpp,frequency,reward,...,truncated,collision_reset_step,bbox_width,bbox_height,x_bound,y_bound,width_bound,height_bound,blue_area,time_since_start
0,1,0,445,401,476,387,3,16.000000,1.966667e+06,0.00,...,False,False,42.0,46.0,0,0,0,0,647,NaN
1,1,0,444,400,433,366,2,16.000000,2.033333e+06,10.00,...,False,False,42.0,46.0,0,0,0,0,651,NaN
2,1,0,444,400,340,421,2,15.841444,1.966667e+06,10.00,...,False,False,42.0,46.0,0,0,0,0,355,NaN
3,3,1,443,397,340,421,2,14.916473,1.966667e+06,-0.01,...,False,False,44.0,48.0,0,0,0,0,321,NaN
4,5,2,443,398,340,421,2,14.606817,1.966667e+06,-0.01,...,False,False,43.0,47.0,0,0,0,0,310,NaN

In [16]:
df = df[df["state"] != 0]
df = df[df["state"] != 1]

In [17]:
diff = df["state"].diff()
df["episode"] = (diff < 0).cumsum()

In [18]:
for episode in range(0, df["episode"].max()):
    episode_df = df[df["episode"] == episode]
    dist_x = episode_df["agent_location_x"].diff()
    dist_y = episode_df["agent_location_y"].diff()
    dist = np.sqrt(dist_x**2 + dist_y**2)
    df.loc[df["episode"] == episode, "distance"] = dist

In [19]:
fps = 12
df["speed"] = df["distance"] * fps
df.to_csv(r'F:\images_paper\CSVs\experiment_data_02_21-14-17_speed.csv')